### ISSUE TITLE
App installs, but doesn't show anything other than menu bar.

### ISSUE THREAD

**Issue by codycodes** [gmattie/Data-Pixels#3]
When I click any of the items in the menu bar, they don't load. Any ideas?

**Comment by gmattie** [comment]
Which OS are you running?

Try uninstalling, rebooting your computer and reinstalling.  Hopefully that will sort everything out.

**Comment by codycodes** [comment]
My girlfriend helped by running `npm run dev`, but it's disconnected from the app. Maybe it's our procedure, but we can't get the desktop app running, just the server in the web browser. Thanks for your tips; we'll try them  👍

**Comment by tammyd** [comment]
Hey - sorry to comment in a closed issue, but were you successful in getting the app to run? I'm also having the same issue. I've built the mac version, when when I open the app I see the icon in the dock as expected and the app's menu bar, but there are no application windows. I've rebooted, etc... nada. Latest versions of macOS Sierra, node, npm.

**Comment by gmattie** [comment]
Unfortunately, I don't have access to a Mac right now so I can only guide you in troubleshooting this issue.  

First, I assume that you've compiled the Mac application on your Mac (and not on a PC) by first running the command `npm run prod` in the `./root` directory, then packaged the compiled code by running the command `npm run package-mac`  in the `~/resources/build` folder.

After compiling the production code, instead of packaging the app try building the app by running the command `npm run build` (instead of `npm run package-mac`) in the `~/resources/build` folder.  This is suppose to display the application the same as if you had just opened the packaged application.  If you are able to build and run the application from the CLI there may be a problem with <a href="https://github.com/electron-userland/electron-packager">Electron Packager</a>.

**Comment by tammyd** [comment]
Thanks for the pointers. Everything's built correctly on my mac I'm using. Same thing happens with `npm run build` target. Poking at mainElectron.js with some strategic `console.log()`'s, it's looking like the `ready-to-show` event never fires. Been digging though https://github.com/electron/electron/issues/7779, but no luck so far. I might dig into this more at some point, but perhaps its an issue on Electron's side, which would be rather annoying...

**Comment by gmattie** [comment]
I agree, that would be quite annoying.  

Maybe the issue has been fixed in the latest version of Electron.  Try updating the Electron version listed in the `~/resources/build/package.json` development dependencies.  Change directory into the `build` folder and enter the CLI command `npm install electron save-dev`.  This will update Electron from the included _v1.6.5_ to _v1.7.5_ (current latest).

**Comment by codycodes** [comment]
for the record, yes tammyd, I am still having the issue. Only the menu bar shows when I run the app. Hopefully can get this to run sometime in the future :)

**Comment by tammyd** [comment]
Updated electron, thats not it. I even went back and used a version that is known to work (in the above linked issue), didn't work either. There's something deeper going on here, but I didn't have time to dig unfortunately.  I can make the screen load (by deleting the `show: false` line) but it's a blank page and doesn't show the contents of the index page, just the background color. If i try and load a different url (the classic example is github.com) it loads fine. Thanks for the project regardless - at the very least it gave me an opportunity to play around with Electron, which i've never tried before!

**Comment by gmattie** [comment]
This is a long shot, but perhaps it has something to do with missing a standard _"Front"_ menu item in the _"Window"_ menu for Mac.  It would be unfortunate if this was the problem, as I haven't come across any documentation _explicitly_ stating that the _"Front"_ menu item should be included for proper functionality with Mac distributions (though it could be argued that it is _implicitly_ suggested in the official documentation example code).

I would try adding the following code to **line 145** of `mainElectron.js`

```
menuTemplate[3].submenu.push(

    {type: 'separator'},
    {role: 'front'}
);
```

Again, my apologies for not having access to a Mac so that I can debug and fix this issue myself, but I guess community involvement is the main benefit of open source software.

**Comment by cwfuller** [comment]
For anyone running into this issue on Mac. Changing `[loadURL](https://github.com/gmattie/Data-Pixels/blob/e6fbce66f30218428d35d907983a318dd8051b17/resources/build/js/main/index.js#L110)` to `loadFile` seems to fix it.

**Comment by gmattie** [comment]
Fixed in **[latest commit](https://github.com/gmattie/Data-Pixels/commit/10d573b5e325b07d4c11dee988441fbf8b6d865b)**
